# Generated by Django 4.2.2 on 2026-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedemail',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
